[package]
name = "sbom-server"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
hyper = { version = "0.14.27", features = ["http1", "server", "tcp"] }
tempfile = "3.8.0"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
