name: Release
on:
  push:
    tags:
      - '**'
jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Toolchains
        run: |
          rustup toolchain install stable
          rustup target add ${{ matrix.target }}
          apt get musl-dev
      - name: Run hooks
        run: |
          cargo build --release --target ${{ matrix.target }} --all-features
